# Generated by Django 4.2.29 on 2026-04-06 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('flex_wip', 'Flex WIP Report'), ('call_plan', 'Yesterday Call Plan'), ('generated', 'Generated Call Plan')], max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(default='Chennai', max_length=100)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('row_count', models.IntegerField(default=0, help_text='Number of data rows')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CallPlanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(db_index=True, max_length=20)),
                ('case_id', models.CharField(blank=True, max_length=20)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('wip_aging', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('segment', models.CharField(blank=True, max_length=50)),
                ('classification', models.CharField(choices=[('PENDING', 'Pending'), ('NEW', 'New'), ('DROPPED', 'Dropped')], max_length=10)),
                ('morning_status', models.CharField(blank=True, max_length=100)),
                ('evening_status', models.CharField(blank=True, max_length=100)),
                ('engineer', models.CharField(blank=True, max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('parts', models.TextField(blank=True)),
                ('month', models.CharField(blank=True, max_length=20)),
                ('wo_otc_code', models.CharField(blank=True, max_length=100)),
                ('hp_owner', models.CharField(blank=True, max_length=100)),
                ('flex_status', models.CharField(blank=True, max_length=100)),
                ('wip_changed', models.CharField(blank=True, max_length=10)),
                ('current_status_tat', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.uploadedfile')),
            ],
            options={
                'ordering': ['-wip_aging'],
            },
        ),
    ]
