# Generated by Django 4.2.29 on 2026-04-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_by',
            field=models.CharField(db_index=True, default='admin', max_length=100),
        ),
    ]
