# Generated by Django 4.2.29 on 2026-04-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
