# Generated by Django 4.2.29 on 2026-04-10 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workspacestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(db_index=True, max_length=20)),
                ('case_id', models.CharField(blank=True, max_length=20)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('wip_aging', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('segment', models.CharField(blank=True, max_length=50)),
                ('engineer', models.CharField(blank=True, max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('parts', models.TextField(blank=True)),
                ('month', models.CharField(blank=True, max_length=20)),
                ('wo_otc_code', models.CharField(blank=True, max_length=100)),
                ('hp_owner', models.CharField(blank=True, max_length=100)),
                ('flex_status', models.CharField(blank=True, max_length=100)),
                ('morning_status', models.CharField(blank=True, max_length=100)),
                ('evening_status', models.CharField(blank=True, max_length=100)),
                ('current_status_tat', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(default='Chennai', max_length=100)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('closed_by', models.CharField(default='admin', max_length=100)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(db_index=True, default='admin', max_length=100)),
                ('city', models.CharField(default='Chennai', max_length=100)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='callplanrecord',
            name='source',
            field=models.CharField(choices=[('analysis', 'From Analysis'), ('manual', 'Manually Added'), ('export', 'From Export')], default='export', max_length=10),
        ),
        migrations.AlterField(
            model_name='callplanrecord',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.uploadedfile'),
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Chennai', max_length=100)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('analyzed_by', models.CharField(default='admin', max_length=100)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('total_count', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('dropped_count', models.IntegerField(default=0)),
                ('result_data', models.JSONField(default=dict)),
                ('callplan_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callplan_analyses', to='api.uploadedfile')),
                ('flex_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flex_analyses', to='api.uploadedfile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.uploadsession')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.uploadsession'),
        ),
    ]
